["news.cnal.com"]
select = ['.col-xs-9:has(h1)']
hide = ['.cnal-collection-con', '.cnal-collection-con ~ *']

["x.com"]
select = ['section[aria-labelledby="accessible-list-2"]']
hide = ['button[aria-label="Translate post"]', 'div[data-testid="inline_reply_offscreen"]', 'h2', 'h2 ~ *']
