["simonwillison.net"]
select = ['#primary .entryPage']
hide = ['.entryFooter a:first-child ~ *']


["www.reddit.com"]
select = ['#main-content']
hide = []


["m.huxiu.com"]
select = ['#m-article-detail-page .js-mask-box']
hide = ['.neirong-shouquan']

["www.huxiu.com"]
select = ['#js-article-read-wrap']

["www.quora.com"]
select = ['#mainContent']
hide = [
  'div[class*="_related_questions"]',
]

["news.cnstock.com"]
select = ['#pager-content']
hide = []

["www.cnstock.com"]
select = ['div[class^="index_leftcontent_"] div[class^="index_wrapper_"]']
hide = [
  '.ant-dropdown-trigger',
  'div[class^="index_bottomBox_"]',
  'div[class^="index_bottomBox_"] ~ *',
  '#commentWrapper'
]

["www.guancha.cn"]
select = ['.left-main']
hide = [
  'div.author-intro > a',
  '.share',
  '#comments-container ~ *',
  '.accusation',
  '.shared-comment',
  'a.comment', 
  'a.recommend',
  'a.collection',
  '.who-recommend',
  '#comments-container-kuang',
  '.cmt-top-pic',
  '.comment-component',
  '.cmt-desc',
  '.tab-control',
]

["en.wikipedia.org"]
select = ['#content']
hide = [
    '.vector-dropdown',
    '.vector-page-toolbar',
    '.vector-column-end',
    '.vector-body-before-content',
]

["www.v2ex.com"]
select = [
  "#Main .box",
]
hide = [
  '#reply-box',
  '#reply-box ~ *',
  '#Rightbar',
  'a[onclick^="reply"]',
  'img.avatar',
]

["cn.wsj.com"]
select = [
  ".article-container",
]
hide = [
  "nav",
  "#cx-snippet-overlay-sign-in-text",
  "#cx-snippet-overlay-sign-in-text ~ *",
  ".aside-container",
  ".article-body-tools",
  "article section ~ *",
  'div[aria-label="Most Popular News"]',
]



["www.news.cn"]
select = [
  ".header-cont",
  ".main-left",
  ".conbox",
]
hide = [
  '.pageShare'
]

["www.xinhuanet.com"]
select = [
    'div.header[datatype="content"]',
    'div.main', 
]
hide = [
    'div.header-top', 
    '.pageShare',
    '.relatedNews', 
    '.relatedNews ~ *',
    '.ad_right',
    '.foot',
    '.adv',
    '.main-right'
]

["www.zaobao.com.sg"]
select = ['article']
hide = ['button', 
    '.paywall-container', 
    'article .articleBody ~ *', 
    '.sticky',
    'a[href*="facebook"]',
    'a[href*="twitter"]',
    'a[href*="wechat"]',
    'a[href*="whatsapp"]',
    'a[href*="/share/"]',
    'a[href^="mailto"]',
]

["m.eeo.com.cn"]
select = [".contact"]
hide = [".contact .t-bottom ~ *", "a.onfocus"]

["www.163.com"]
select = [
  ".post_main",
]
hide = [
  "#no-tie",
  ".post_crumb",
  ".post_jubao",
  ".post_top",
  ".post_author",
  "#post_comment_area",
  ".post_recommends",
  ".tie-areas",
  "#tie", ".post_statement", ".post_next"
]

["www.21jingji.com"]
select = [
  ".main", 
  'div:has(> h2)'
]
hide = ['.detailShare', '.share-wrap']

["www.thepaper.cn"]
select = ['div[class^="index_wrapper_"]:has(h1)']
hide = [
    'div[class*="copyrightBox"]',
    'div[class*="bottomBox"]',
    'div[class^="index_audio_"]',
    '.ant-dropdown-trigger',
]


["www.investing.com"]
select = ['div.flex-col:has(#articleTitle)']
hide = [
    'div[data-test="contextual-subscription-hook"]',
    'div.flex-col:has(#articleTitle) #comments ~ *',
    '.sticky',
    'div.text-center:has(a[id^="article-ad-disclosure"])',
    'div[data-ad-label="Advertisement"]',
]

["news.qq.com"]
select = [
  ".content-article",
]
hide = [
  ".statement",
  ".qqcom-follow-button",
  ".author-avatar"
]

["news.cnal.com"]
select = ['.col-xs-9:has(h1)']
hide = ['.cnal-collection-con', '.cnal-collection-con ~ *']

["x.com"]
select = ['div[aria-label^="Timeline: Conversation"]']
hide = ['button[aria-label="Translate post"]', 
    'div[aria-live="polite"]',
    'div[data-testid="inline_reply_offscreen"]', 
    'div[aria-label^="Timeline"] h2', 
    'div[data-testid="cellInnerDiv"]:has(h2) ~ *',
    'div[data-testid="cellInnerDiv"] h2 ~ *',
    ]



["tech.ifeng.com"]
select = ['div[class^="index_artical_"]']
hide = ['div[class*="share_box"]', 
    'div[class*="comment_box"]',
    'div[class^="index_vote_box"]',
    '#articleBottomAdAuto',
    'div[class^="index_comment_box"]',
]

["xueqiu.com"]
select = [
  ".article__container",
  ".article__author",
  "article",
  ".comment__list",
  ".modal_content",
]
hide = [
  "div.article__author a.avatar",
  ".ai_abstract_feedback",
]

["36kr.com"]
select = ['.article-mian-content']
hide = ['.article-footer-txt']

