["s.weibo.com"]
select = [".ai_module", ".card-wrap"]
hide = [".operate_area", ".material_status_text", ".wbicon"]

["www.wsj.com"]
select = ['main']
hide = [
  'article ~ *',
  'section ~ *',
  '#cx-snippet-overlay-sign-in-text', 
  '#cx-snippet-overlay-sign-in-text ~ *',
]

["www.reuters.com"]
select = [
  'article',
  '[class^="article__content_"]',
  '[class^="article-module__content"]',
]
hide = [
  '[class*="article-body__trust-badge_"]',
  '[class*="article-body__trust-badge_"] ~ div',
  "nav",
  '[class*="license-content-button"]',
  'a[data-testid="LicenceContentButton"]',
  'p[class*="article-body-module__trust-badge_"]',
  '.other-stories-container',
]


["www.anthropic.com"]
select = ['#main-content']
hide = ['article ~ *', 'div[class^="ToutCallout"]']

["stock.10jqka.com.cn"]
select = [
  ".main-fl",
]
hide = [
  ".dianzan",
  ".share-bottom",
  ".politics-hide",
]

["stcn.com"]
select = ['.column-810']
hide = ['.detail-content-tags', '.detail-content-tags ~ *']

["www.economist.com"]
select = ["main#content"]
hide = [
  "#article-tags", 
  "#article-tags ~ *", 
  'div:has(> #article-tags) ~ *',
  'div[data-testid="morefrom-sectionheader"]',
  'div[data-testid="morefrom-sectionheader"] ~ *',
  'i:has(a[href^="https://www.economist.com/newsletters/"])'
]

["news.ycombinator.com"]
select = [
  "#bigbox",
]
hide = [
  'form', '.reply', '.navs',
  'a[href^="hide"]',
  'a.hnpast',
  'a[href^="fav"]',
]

["arxiv.org"]
select = ['.leftcolumn']

["spaces.ac.cn"]
select = [".Post", "#comments .AllComments"]
hide = ['#content_tips', '#content_tips ~ *']

["www.newyorker.com"]
select = ['article']
hide = []

["lobste.rs"]
select = ['#inside']
hide = ['form']

["www.gamelook.com.cn"]
select = [
  ".entry-head",
  ".entry-content",
]
hide = ['.entry-fontsize', '.entry-copyright']

["www.xinhuanet.com"]
select = [
  "div.header",
  "div.main",
]
hide = [
  ".news-link",
  ".news-position",
  "div.header-top",
  ".fllow1-wap",
  ".pageShare",
  ".relatedNews",
  ".relatedNews ~ *",
  ".ad_right",
  ".foot",
  ".adv",
  ".main-right",
  ".part-right",
  ".zan-wap",
  ".zan-wap ~ *",
  ".relate-news",
  ".relate-news ~ *",
  ".p2-nav-wap",
  ".p2-nav-wap ~ *",  
]

["www.zhihu.com"]
select = ['.QuestionHeader-content', '.Question-mainColumn']
hide = ['.QuestionHeader-topics', '.Question-mainColumnLogin']

["finance.ifeng.com"]
select = [
  "#artical",
  "h1",
  '[class^="index_infoboxLink_"]',
  '[class^="index_main_content_"]',
]
hide = ['.share', '#artical_real ~ *']


["politics.people.com.cn"]
select = ['.text_title', '#rwb_zw', 'section.left']
hide = ['#ops_share', 'aside.tools',
  'a[href="http://mms.people.com.cn/GB/"]',
  '#p_content ~ *',
  '.message',
  '.message ~ *',
]

["finance.people.com.cn"]
select = [
  "div.col:has(h1)",
  "h1",
  ".author",
  ".channel",
  ".rm_txt_con",
]
hide = [
  'div.edit ~ *',
  "div.rm_relevant",
  "div.rm_relevant ~ *",
]


["china.caixin.com"]
select = ['#the_content']
hide = ['.pip', 'a.pc-aivoice', 'p.aitt', '#chargeWall', '#chargeWall ~ *']

["m.ebrun.com"]
select = ['article']
hide = ['.ai-quick-read']

["cn.wsj.com"]
select = [
  '.article-container',
  'div[data-testid^="bigtop-headline"]',
  "#big-top-caption",
  "article",
]
hide = [
  "nav",
  "#cx-snippet-overlay-sign-in-text",
  "#cx-snippet-overlay-sign-in-text ~ *",
  ".aside-container",
  ".article-body-tools",
  "article section ~ *",
  'div[aria-label="Most Popular News"]',
  'div:has(section) ~ *',
]

["simonwillison.net"]
select = ['#primary .entryPage']
hide = ['.entryFooter a:first-child ~ *']


["www.reddit.com"]
select = ['#main-content']
hide = []


["m.huxiu.com"]
select = ['#m-article-detail-page .js-mask-box']
hide = ['.neirong-shouquan']

["www.huxiu.com"]
select = ['#js-article-read-wrap']

["www.quora.com"]
select = ['#mainContent']
hide = [
  'div[class*="_related_questions"]',
]

["news.cnstock.com"]
select = ['#pager-content']
hide = []

["www.cnstock.com"]
select = ['div[class^="index_leftcontent_"] div[class^="index_wrapper_"]']
hide = [
  '.ant-dropdown-trigger',
  'div[class^="index_bottomBox_"]',
  'div[class^="index_bottomBox_"] ~ *',
  '#commentWrapper'
]

["www.guancha.cn"]
select = ['.left-main']
hide = [
  'div.author-intro > a',
  '.share',
  '#comments-container ~ *',
  '.accusation',
  '.shared-comment',
  'a.comment', 
  'a.recommend',
  'a.collection',
  '.who-recommend',
  '#comments-container-kuang',
  '.cmt-top-pic',
  '.comment-component',
  '.cmt-desc',
  '.tab-control',
]

["en.wikipedia.org"]
select = ['#content']
hide = [
    '.vector-dropdown',
    '.vector-page-toolbar',
    '.vector-column-end',
    '.vector-body-before-content',
]

["www.v2ex.com"]
select = [
  "#Main .box",
]
hide = [
  '#reply-box',
  '#reply-box ~ *',
  '#Rightbar',
  'a[onclick^="reply"]',
  'img.avatar',
]


["www.news.cn"]
select = [
  ".header-cont",
  ".main-left",
  ".conbox",
]
hide = [
  '.pageShare'
]


["www.zaobao.com.sg"]
select = ['article']
hide = ['button', 
    '.paywall-container', 
    'article .articleBody ~ *', 
    '.sticky',
    'a[href*="facebook"]',
    'a[href*="twitter"]',
    'a[href*="wechat"]',
    'a[href*="whatsapp"]',
    'a[href*="/share/"]',
    'a[href^="mailto"]',
]

["m.eeo.com.cn"]
select = [".contact"]
hide = [".contact .t-bottom ~ *", "a.onfocus"]

["www.163.com"]
select = [
  ".post_main",
]
hide = [
  "#no-tie",
  ".post_crumb",
  ".post_jubao",
  ".post_top",
  ".post_author",
  "#post_comment_area",
  ".post_recommends",
  ".tie-areas",
  "#tie", ".post_statement", ".post_next"
]

["www.21jingji.com"]
select = [
  ".main", 
  'div:has(> h2)'
]
hide = ['.detailShare', '.share-wrap']

["www.thepaper.cn"]
select = ['div[class^="index_wrapper_"]:has(h1)']
hide = [
    'div[class*="copyrightBox"]',
    'div[class*="bottomBox"]',
    'div[class^="index_audio_"]',
    '.ant-dropdown-trigger',
]


["www.investing.com"]
select = ['div.flex-col:has(#articleTitle)']
hide = [
    'div[data-test="contextual-subscription-hook"]',
    'div.flex-col:has(#articleTitle) #comments ~ *',
    '.sticky',
    'div.text-center:has(a[id^="article-ad-disclosure"])',
    'div[data-ad-label="Advertisement"]',
]

["news.qq.com"]
select = [
  ".content-article",
]
hide = [
  ".statement",
  ".qqcom-follow-button",
  ".author-avatar"
]

["news.cnal.com"]
select = ['.col-xs-9:has(h1)']
hide = ['.cnal-collection-con', '.cnal-collection-con ~ *']

["x.com"]
select = ['div[aria-label^="Timeline: Conversation"]']
hide = ['button[aria-label="Translate post"]', 
    'div[aria-live="polite"]',
    'div[data-testid="inline_reply_offscreen"]', 
    'div[aria-label^="Timeline"] h2', 
    'div[data-testid="cellInnerDiv"]:has(h2) ~ *',
    'div[data-testid="cellInnerDiv"] h2 ~ *',
    ]



["tech.ifeng.com"]
select = ['div[class^="index_artical_"]']
hide = ['div[class*="share_box"]', 
    'div[class*="comment_box"]',
    'div[class^="index_vote_box"]',
    '#articleBottomAdAuto',
    'div[class^="index_comment_box"]',
]

["xueqiu.com"]
select = [
  ".article__container",
  ".article__author",
  "article",
  ".comment__list",
  ".modal_content",
]
hide = [
  "div.article__author a.avatar",
  ".ai_abstract_feedback",
]

["36kr.com"]
select = ['.article-mian-content']
hide = ['.article-footer-txt']

