["news.cnal.com"]
select = ['.col-xs-9:has(h1)']
hide = ['.cnal-collection-con', '.cnal-collection-con ~ *']

["x.com"]
select = ['div[aria-label^="Timeline: Conversation"]']
hide = ['button[aria-label="Translate post"]', 
    'div[aria-live="polite"]',
    'div[data-testid="inline_reply_offscreen"]', 
    'div[aria-label^="Timeline"] h2', 
    'div[data-testid="cellInnerDiv"]:has(h2) ~ *',
    'div[data-testid="cellInnerDiv"] h2 ~ *',
    ]

["cn.wsj.com"]    
select = ['.article-container']
hide = ['nav', 
    '#cx-snippet-overlay-sign-in-text', 
    '#cx-snippet-overlay-sign-in-text ~ *',
    '.aside-container', 
    '.article-body-tools', 
    'article section ~ *',
    ]

["tech.ifeng.com"]
select = ['div[class^="index_artical_"]']
hide = ['div[class*="share_box"]', 
    'div[class*="comment_box"]',
    'div[class^="index_vote_box"]',
    '#articleBottomAdAuto',
    'div[class^="index_comment_box"]',
]

["xueqiu.com"]
select = [
  ".article__container",
  ".article__author",
  "article",
  ".comment__list",
  ".modal_content",
]
hide = [
  "div.article__author a.avatar",
  ".ai_abstract_feedback",
]
